apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-db
  namespace: suxess-it-qa
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demo-db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-db
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          value: demodb
        - name: MYSQL_PASSWORD
          value: demodb
        - name: MYSQL_DATABASE
          value: demodb
        image: registry.redhat.io/rhel9/mysql-80@sha256:f3d2a4faa35c80d4b342fd5a427098ce250f27c39704c8cf798a05293aaefe07
        imagePullPolicy: IfNotPresent
        name: container
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
