{{- range $stage, $values := .Values }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $values.application_id }}-{{ $stage }}
  namespace: suxess-it-{{ $stage }}
  annotations:
    link.argocd.argoproj.io/external-link: http://{{ $values.application_id }}-{{ $stage }}.suxess-it-{{ $stage }}.apps.cluster1.mcp.pitagora.at
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ $values.application_id }}-{{ $stage }}
  {{- end }}
